CREATE TABLE IF NOT EXISTS d_ai_workflow_checkpoint (
    id BIGINT NOT NULL AUTO_INCREMENT,
    checkpoint_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(64) NOT NULL,
    node_code VARCHAR(64) NOT NULL,
    node_status VARCHAR(32) NOT NULL,
    state_json JSON NULL,
    input_json JSON NULL,
    output_json JSON NULL,
    error_message VARCHAR(1024) NULL,
    version_no INT NOT NULL DEFAULT 1,
    operator_id VARCHAR(64) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edit_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status TINYINT NOT NULL DEFAULT 1,
    ext_json JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_workflow_checkpoint (checkpoint_id),
    KEY idx_ai_workflow_checkpoint_run_node (run_id, node_code),
    KEY idx_ai_workflow_checkpoint_status (node_status, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS d_ai_nl2sql_semantic_catalog (
    id BIGINT NOT NULL AUTO_INCREMENT,
    catalog_id VARCHAR(64) NOT NULL,
    datasource_key VARCHAR(128) NOT NULL,
    semantic_type VARCHAR(32) NOT NULL,
    semantic_key VARCHAR(128) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    dataset_name VARCHAR(128) NULL,
    table_name VARCHAR(128) NULL,
    column_name VARCHAR(128) NULL,
    expression_sql TEXT NULL,
    allowed_view VARCHAR(128) NULL,
    sensitivity_level VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    example_sql TEXT NULL,
    version_no INT NOT NULL DEFAULT 1,
    catalog_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    operator_id VARCHAR(64) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edit_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status TINYINT NOT NULL DEFAULT 1,
    ext_json JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_nl2sql_catalog_key (datasource_key, semantic_type, semantic_key, version_no),
    KEY idx_ai_nl2sql_catalog_dataset (dataset_name, status),
    KEY idx_ai_nl2sql_catalog_status (catalog_status, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS d_ai_purchase_reservation_action (
    id BIGINT NOT NULL AUTO_INCREMENT,
    reservation_id VARCHAR(96) NOT NULL,
    action_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(64) NOT NULL,
    program_id BIGINT NOT NULL,
    ticket_category_id BIGINT NOT NULL,
    ticket_count INT NOT NULL,
    reservation_status VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    expires_at DATETIME NULL,
    released_at DATETIME NULL,
    release_reason VARCHAR(255) NULL,
    operator_id VARCHAR(64) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edit_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status TINYINT NOT NULL DEFAULT 1,
    ext_json JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_purchase_reservation (reservation_id),
    UNIQUE KEY uk_ai_purchase_reservation_idempotency (idempotency_key),
    KEY idx_ai_purchase_reservation_action (action_id, status),
    KEY idx_ai_purchase_reservation_expires (expires_at, reservation_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS d_ai_knowledge_release (
    id BIGINT NOT NULL AUTO_INCREMENT,
    release_id VARCHAR(64) NOT NULL,
    knowledge_scope VARCHAR(64) NOT NULL,
    topic_code VARCHAR(128) NULL,
    draft_version VARCHAR(64) NOT NULL,
    published_version VARCHAR(64) NULL,
    previous_version VARCHAR(64) NULL,
    release_status VARCHAR(32) NOT NULL,
    qdrant_collection VARCHAR(128) NULL,
    qdrant_alias VARCHAR(128) NULL,
    es_index VARCHAR(128) NULL,
    es_alias VARCHAR(128) NULL,
    quality_report_json JSON NULL,
    rollback_reason VARCHAR(512) NULL,
    operator_id VARCHAR(64) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edit_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status TINYINT NOT NULL DEFAULT 1,
    ext_json JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_knowledge_release (release_id),
    KEY idx_ai_knowledge_release_scope (knowledge_scope, topic_code, release_status),
    KEY idx_ai_knowledge_release_version (published_version, previous_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS d_ai_customer_work_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    work_item_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(64) NULL,
    ticket_id VARCHAR(64) NULL,
    user_id BIGINT NULL,
    skill_group VARCHAR(64) NULL,
    work_status VARCHAR(32) NOT NULL,
    takeover_status VARCHAR(32) NOT NULL DEFAULT 'AI_HANDLING',
    priority VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    sla_due_at DATETIME NULL,
    assigned_to VARCHAR(64) NULL,
    conclusion VARCHAR(512) NULL,
    satisfaction_score INT NULL,
    operator_id VARCHAR(64) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edit_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status TINYINT NOT NULL DEFAULT 1,
    ext_json JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_customer_work_item (work_item_id),
    KEY idx_ai_customer_work_item_ticket (ticket_id, status),
    KEY idx_ai_customer_work_item_sla (sla_due_at, work_status),
    KEY idx_ai_customer_work_item_assignee (assigned_to, work_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS d_ai_ops_evidence_provider (
    id BIGINT NOT NULL AUTO_INCREMENT,
    provider_id VARCHAR(64) NOT NULL,
    provider_type VARCHAR(32) NOT NULL,
    provider_name VARCHAR(128) NOT NULL,
    provider_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    endpoint VARCHAR(256) NULL,
    weight INT NOT NULL DEFAULT 100,
    operator_id VARCHAR(64) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edit_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status TINYINT NOT NULL DEFAULT 1,
    ext_json JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_ops_evidence_provider (provider_id),
    KEY idx_ai_ops_evidence_provider_type (provider_type, provider_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS d_ai_ops_runbook (
    id BIGINT NOT NULL AUTO_INCREMENT,
    runbook_id VARCHAR(64) NOT NULL,
    service_name VARCHAR(128) NULL,
    scenario_key VARCHAR(128) NOT NULL,
    title VARCHAR(255) NOT NULL,
    recommendation TEXT NULL,
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW',
    executable TINYINT NOT NULL DEFAULT 0,
    review_required TINYINT NOT NULL DEFAULT 1,
    runbook_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    operator_id VARCHAR(64) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edit_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status TINYINT NOT NULL DEFAULT 1,
    ext_json JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_ops_runbook (runbook_id),
    KEY idx_ai_ops_runbook_scenario (scenario_key, service_name, runbook_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS d_ai_route_eval_case (
    id BIGINT NOT NULL AUTO_INCREMENT,
    case_id VARCHAR(64) NOT NULL,
    suite_code VARCHAR(64) NOT NULL,
    user_message TEXT NOT NULL,
    expected_route VARCHAR(64) NOT NULL,
    expected_skill VARCHAR(64) NULL,
    case_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    operator_id VARCHAR(64) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edit_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status TINYINT NOT NULL DEFAULT 1,
    ext_json JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_route_eval_case (case_id),
    KEY idx_ai_route_eval_case_suite (suite_code, case_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS d_ai_route_eval_result (
    id BIGINT NOT NULL AUTO_INCREMENT,
    result_id VARCHAR(64) NOT NULL,
    eval_run_id VARCHAR(64) NOT NULL,
    case_id VARCHAR(64) NOT NULL,
    actual_route VARCHAR(64) NULL,
    actual_skill VARCHAR(64) NULL,
    passed TINYINT NOT NULL DEFAULT 0,
    score DECIMAL(8,4) NOT NULL DEFAULT 0,
    error_message VARCHAR(1024) NULL,
    operator_id VARCHAR(64) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edit_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status TINYINT NOT NULL DEFAULT 1,
    ext_json JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_route_eval_result (result_id),
    KEY idx_ai_route_eval_result_run (eval_run_id, passed),
    KEY idx_ai_route_eval_result_case (case_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
