client {
  application.id = "order-service"
  transaction.service.group = "order-service"
}

service {
  vgroupMapping.order-service = "order-service-map"
  grouplist.order-service-map = "127.0.0.1:8091"
  disableGlobalTransaction = false
  enableDegrade = false
}
