transport {
  type = "TCP"
  server = "NIO"
  heartbeat = true
  enableClientBatchSendRequest = true
  threadFactory {
    bossThreadPrefix = "NettyBoss"
    workerThreadPrefix = "NettyServerNIOWorker"
    serverExecutorThreadPrefix = "NettyServerBizHandler"
    shareBossWorker = false
    clientSelectorThreadPrefix = "NettyClientSelector"
    clientSelectorThreadSize = 1
    clientWorkerThreadPrefix = "NettyClientWorkerThread"
    workerThreadSize = "default"
    bossThreadSize = 1
  }
  shutdown {
    wait = 3
  }
}

service {
  vgroupMapping.default_tx_group = "default"
  disableGlobalTransaction = false
  enableDegrade = false
  grouplist.default = "seata:8091"
  max.commit.retry.timeout = "-1"
  max.rollback.retry.timeout = "-1"
}

client {
  undo {
    dataValidation = true
    logSerialization = "jackson"
  }
}

store {
  mode = "db"
  lock {
    mode = "db"
  }
  session {
    mode = "db"
  }
  db {
    datasource = "druid"
    dbType = "mysql"
    driverClassName = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://mysql:3306/seata?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai"
    user = "root"
    password = "root"
    minConn = 5
    maxConn = 30
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    distributedLockTable = "distributed_lock"
    queryLimit = 100
    maxWait = 5000
  }
}

server {
  service-port = 8091
  maxCommitRetryTimeout = -1
  maxRollbackRetryTimeout = -1
  recovery {
    committingRetryPeriod = 1000
    asynCommittingRetryPeriod = 1000
    rollbackingRetryPeriod = 1000
    timeoutRetryPeriod = 1000
  }
}

metrics {
  enabled = false
}
